services:
  #mailhog:
  #  image: mailhog/mailhog
  #  container_name: mailhog
  #  ports:
  #    - "8025:8025" # Веб-интерфейс: http://localhost:8025
  #    - "1025:1025" # SMTP порт
  #  networks:
  #    - saas_network

  notification-service:
    build: . # Укажите ".", если compose.yml лежит в папке notification-service
    container_name: notification-service
    ports:
      - "8009:8000"
    environment:
  #    MAIL_USER: ${MAIL_USER}
  #    MAIL_PASSWORD: ${MAIL_PASSWORD}
  #    MAIL_SERVER: ${MAIL_SERVER}
  #    MAIL_PORT: ${MAIL_PORT}
  #    MAIL_FROM: ${MAIL_FROM}
  #    KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}

    #depends_on:
    #  - mailhog
    networks:
      - saas_network
    restart: unless-stopped

networks:
  saas_network:
    driver: bridge
    external: true
